# Generated by Django 3.1.1 on 2020-10-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0002_find_love_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('p_number', models.CharField(max_length=10)),
                ('e_mail', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('postcode', models.CharField(max_length=10)),
                ('number_slip', models.IntegerField()),
                ('sell_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='love',
            name='love_type',
        ),
        migrations.DeleteModel(
            name='Find',
        ),
        migrations.DeleteModel(
            name='Love',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
