# Generated by Django 3.1.1 on 2020-10-22 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0003_auto_20201022_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sell',
            name='sell_date',
        ),
    ]
