# Generated by Django 3.1.1 on 2020-10-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0006_auto_20201022_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='comment',
            name='Phone_Number',
            field=models.CharField(max_length=10),
        ),
    ]
