# Generated by Django 3.1.1 on 2020-10-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0008_comment2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment2',
            name='A_ddess',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='comment2',
            name='P_code',
            field=models.CharField(max_length=100),
        ),
    ]
