# Generated by Django 3.1.1 on 2020-10-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0011_auto_20201025_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment2',
            name='P_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='comment2',
            name='Phone',
            field=models.IntegerField(),
        ),
    ]
