# Generated by Django 3.1.1 on 2020-10-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0014_auto_20201025_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment2',
            name='A_ddess',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='comment2',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
