# Generated by Django 3.1.1 on 2020-10-25 10:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0015_auto_20201025_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment2',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 10, 25, 10, 31, 56, 530143, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
