# Generated by Django 3.1.1 on 2020-10-25 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0016_comment2_created_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment2',
            old_name='created_on',
            new_name='date',
        ),
    ]
